#config:
#  crontime: 0 * * * * ?
#
#mail: bek@prog-matik.ru

#spring:
#    jpa:
#        hibernate:
#            ddl-auto: create
#        properties:
#                jdbc:
#                    batch_size:1000
#    datasource:
#        driver: org.postgresql.Driver
#        url:  jdbc:postgresql:gistimer?stringtype=unspecified
#        username: postgres
#        password: 222

driver: org.firebirdsql.jdbc.FBDriver
databaseurl: jdbc:firebirdsql:172.16.0.203:fias
user: SYSDBA
password: masterkey
encoding: WIN1251

client:
  default-uri: https://fias.nalog.ru/WebServices/Public/DownloadService.asmx
  ssl:
    trust-store: classpath:jks/nalog.ru.jks
    trust-store-password: nalog.ru-pass

batch_size: 1000
proceedperiod: 86400000
downloadperiod: 3600000
house_query: update or insert into house0 (houseid, aoguid, buildnum, houseguid, housenum, strstatus) values(?, ?, ?, ?, ?, ?)matching(houseid)
addrobj_query: update or insert into addrobj(aoguid,aoid,aolevel,citycode,currstatus,formalname,nextid,offname,operstatus,parentguid,placecode,previd,regioncode,shortname,streetcode,livestatus)values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) matching(aoid)

logging:
  level:
    root: info
  file: log/application.log