#config:
#  crontime: 0 * * * * ?
#
#mail: bek@prog-matik.ru

#spring:
#    jpa:
#        hibernate:
#            ddl-auto: create
#        properties:
#                jdbc:
#                    batch_size:1000
#    datasource:
#        driver: org.postgresql.Driver
#        url:  jdbc:postgresql:gistimer?stringtype=unspecified
#        username: postgres
#        password: 222

driver: org.firebirdsql.jdbc.FBDriver
databaseurl: 172.16.0.18:/opt/firebird/bases/FIAS.fdb
username: SYSDBA
password: 111
encoding: WIN1251

fiasurl: http://fias.nalog.ru/WebServices/Public/DownloadService.asmx
batch_size: 10000
proceedperiod: 86400000
downloadperiod: 3600000